##
##           the creative              /$$                        /$$
##                                    | $$                       | $$
##      /$$$$$$$  /$$$$$$  /$$$$$$$  /$$$$$$    /$$$$$$  /$$$$$$ | $$
##     /$$_____/ /$$__  $$| $$__  $$|_  $$_/   /$$__  $$|____  $$| $$
##    | $$      | $$$$$$$$| $$  \ $$  | $$    | $$  \__/ /$$$$$$$| $$
##    | $$      | $$_____/| $$  | $$  | $$ /$$| $$      /$$__  $$| $$
##    |  $$$$$$$|  $$$$$$$| $$  | $$  |  $$$$/| $$     |  $$$$$$$| $$
##    \_______/ \_______/|__/  |__/   \___/  |__/      \_______/|__/
##                                                  plugin by unnamed
##

#
# Welcome to the creative-central configuration!
#
#
# A few notes before you start:
#
#   -   If you want to use special characters in the config file, you need
#       to save the file using UTF-8, not ANSI or any other encoding
#
#   -   We use MiniMessage for all messages, for more information visit:
#       https://docs.advntr.dev/minimessage/index.html
#
#
# If you need help with the configuration, feel free to contact us on
#   -   Discord: https://discord.gg/xbba2fy
#

##
## Settings for the resource pack sending. In this section, we specify
## some options for the resource pack request and some extra options on
## how and when to send the resource pack to the player
##
send:
    # Options for the resource pack download request
    request:
        # True to tell the player that they need to accept the resource-pack, false if the
        # resource-pack installation is optional
        #
        # IMPORTANT: Please note that this is purely client-side, the server will not necessarily
        #    kick the player if they don't accept the resource pack, you need to configure that in
        #    the 'feedback' section, specifically in the 'declined' section
        required: true

        # (Optional) Message shown to players when they join for the first time
        # They are asked to use the server resource pack and this message is
        # shown in the screen (1.17 and above, versions before 1.17 don't have this)
        prompt: |-
            <aqua>金幣爭霸戰
            <green>請接受使用伺服器資源包以享受完整的伺服器體驗

    # Determines how much time to wait before sending the resource pack
    # to the player. Set to 0 or less to send immediately.
    delay: 0



##
## In this section, we specify the actions to perform when the player
## accepts, declines, loads or fails to download the resource pack
##
## Currently, the following actions are supported:
## - title:     Shows a title to the player (subtitle, fade-in, stay and fade-out options are supported as well)
## - message:   Sends a message to the player
## - kick:      Kicks the player from the server with a custom reason message
##
feedback:
    # Actions to perform when the player accepts the resource pack and starts downloading it
    # These actions will be performed instantly after the player clicks the "Yes" button
    # in the resource pack download screen
    accepted:
        - title:
              title: '<yellow>加載中...'
              subtitle: '<gray>正在下載資源包...'
              fade-in: 0
              stay: 90
              fade-out: 0
        - message: '<aqua>資源包管理 <gray>| <yellow>正在下載資源包...'

    # Actions to perform when the player successfully finishes downloading the resource pack
    # These actions will be performed after the (resource pack download) loading screen on the
    # client disappears
    success:
        -   title:
                title: '<green>資源包已正確下載!'
                subtitle: '<gray>歡迎來到金幣爭霸戰!'
                fade-in: 10
                stay: 50
                fade-out: 10
        -   message: '<aqua>資源包管理 <gray>| <green>資源包已正確下載!'
    # Actions to perform when the player declines the resource pack
    declined:
        - kick: "你必須接受資源包才能在此伺服器遊玩。"
    # Actions to perform when the player fails to download the resource pack
    failed:
        - kick: "無法下載資源包，發生錯誤。請聯繫管理員。(FAILED)"
    # Actions to perform when the player successfully downloads (but still not tries to apply) the resource-pack
    downloaded: []
    # Actions to perform when the player's client detects an invalid URL (our fault!)
    invalid-url:
        - kick: "無法下載資源包，發生錯誤。請聯繫管理員。(INVALID_URL)"
    # Actions to perform when the player's client fails to apply the resource-pack
    failed-reload:
        - kick: "無法下載資源包，發生錯誤。請聯繫管理員。(FAILED_RELOAD)"
    # Actions to perform when the player's client fails to apply the resource-pack
    discarded:
        - kick: "無法應用資源包，發生錯誤。請聯繫管理員 (DISCARDED)"



##
## Settings for Resource Pack exporting, in this section we specify
## how to export the generated resource pack
##
export:
    #
    # How should we export the generated resource pack?
    # |
    # |--> 'mcpacks' (default) (hosted)
    # |     Uploads the generated resource pack to https://mc-packs.net/,
    # |     a free resource pack hosting service (Consider donating to them)
    # |
    # |--> 'localhost' (hosted)
    # |     Opens a local HTTP server to serve resource packs, no third parties,
    # |     extra configuration is required (you need to open a new port in
    # |     your server and enable the 'localhost' setting, see below)
    # |
    # |--> 'polymath <url> <secret>' (hosted)
    # |     Uploads the generated resource pack to a Polymath server. (Oraxen's
    # |     resource pack server)

    #
    # | Note: The plugin will not prompt players to download the resource
    # |       pack if the export method is not hosted, this is because
    # |       Minecraft requires an URL to be sent to the player in order
    # |       to download the resource pack
    type: 'mcpacks'

    # Configuration for locally hosting resource packs
    localhost:
        # True to enable and start the HTTP server, false to disable it
        # (Disabled by default)
        #
        # IMPORTANT: Note that setting the export type to 'localhost' will not
        # automatically enable the HTTP server, you need to set this to true
        enabled: false

        # The address that the resource-pack server should use, in most
        # cases, you can just put your server's public IP address.
        # If you leave this option empty, the plugin will automatically detect
        #   your server's public API address by using a "what is my ip" service
        address: ''

        # The resource pack host port (7270 by default)
        port: 7270

        # The public address for the resource-pack server, this is the address
        # sent to the players when they are asked to download the server's
        # resource-pack.
        # If you leave this option empty, it will take the same value as "address"
        public-address: ''



command:
    # Messages sent to the player when they execute any subcommand under
    # the '/creative' command, and they don't have permission. For more
    # customization, there are messages for each subcommand
    no-permission:
        help: "<red>您沒有權限使用此命令。"
        reload: "<red>您沒有權限使用此命令。"
        apply:
            self: "<red>您沒有權限使用此命令。"
            others: "<red>您沒有權限發送資源包給其他玩家。"
    usage:
        unknown: "<red>未知的子命令。輸入 '/central help' 獲取幫助。"
        help: "<red>正確用法: /central [help|?]"
        reload: "<red>正確用法: /central reload"
        apply:
            self: "<red>正確用法: /central apply"
            others: "<red>正確用法: /central apply [target]"
    apply:
        no-resource-pack: "<red>似乎資源包尚未準備好。這可能是因為資源包的匯出方式不是**託管**的，或插件尚未完全啟用"
        no-player: "<red>您必須是一名玩家才能使用此命令"
        player-not-found: "<red>找不到該名稱的玩家"
        no-players: "<red>目前沒有任何玩家在線"
    feedback:
        reload: "<green>Config 已成功重新加載。"
        apply: "<green>資源包已發送！"
    help: |-
        <aqua>/central help <gray>- <white>顯示此幫助訊息
        <aqua>/central apply [target] <gray>- <white>發送資源包給指定玩家（如果未指定則發送給自己）
        <aqua>/central reload <gray>- <white>重新加載插件配置，重新生成、匯出並發送資源包


##
## (ADVANCED AND INTERNAL SETTINGS)
## You probably don't want to touch anything below
##

# This setting specifies what "What is my ip" services we can use in order to obtain
# the server's IP address (which is sent to the client to download the resource pack)
--what-is-my-ip-services:
    - 'https://api.ipify.org'
    - 'https://api4.my-ip.io/ip'
    - 'https://api-ipv4.ip.sb/ip'